###########
## RULES ##
###########

# window
windowrule=tags:7,appid:Discord
windowrule=tags:7,appid:Steam

# tag (workspace)

# layer
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi
