###################
### KEYBINDINGS ###
###################

$mod = SUPER # Sets "Windows" key as main modifier

# focus moving
bind = $mod, H, movefocus, l    #left
bind = $mod, J, movefocus, d    #down
bind = $mod, K, movefocus, u    #up
bind = $mod, L, movefocus, r    #right

bind = $mod, z, submap, move
submap = move
    bind = $mod, H, movewindow, l
    bind = $mod, J, movewindow, d
    bind = $mod, K, movewindow, u
    bind = $mod, L, movewindow, r

    # layout:scrolling specific
    bind = $mod Shift, H,layoutmsg, swapcol l
    bind = $mod Shift, L,layoutmsg, swapcol r

    bind  =  , escape, submap, reset
submap = reset

bind = $mod, x, submap, resize
submap = resize
    binde = $mod, H, resizeactive, -20 0
    binde = $mod, J, resizeactive, 0 -20
    binde = $mod, K, resizeactive, 0 20 
    binde = $mod, L, resizeactive, 20 0

    # layout:scrolling specific
    binde = $mod Shift, H, layoutmsg, colresize -0.02
    binde = $mod Shift, L, layoutmsg, colresize +0.02
    bind = $mod, Q, layoutmsg, colresize +conf 
    bind = $mod, 0, layoutmsg, fit all
    bind = $mod, 2, layoutmsg, colresize all 0.5
    bind = $mod, 3, layoutmsg, colresize all 0.333

    bind  =  , escape, submap, reset
submap = reset

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mod, T, exec, $terminal
bind = $mod, W, killactive,
bind = $mod, E, exec, $fileManager
bind = $mod, F, togglefloating,
bind = $mod, R, exec, $menu -show combi
bind = $mod, P, pseudo, # dwindle
bind = $mod, V, togglesplit, # dwindle
bind = Control Shift, escape, exec, $terminal -e btop -p 0
bind = Control Alt, L, exec, hyprlock

bind = Alt, Tab, focusmonitor, +1

bind = $mod, C, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy
bind = $mod, B, exec, firefox

# Switch workspaces with mod + [0-9]
# See https://github.com/hyprwm/contrib/tree/main/try_swap_workspace for script used
bind = $mod, 1, exec, try_swap_workspace 1
bind = $mod, 2, exec, try_swap_workspace 2
bind = $mod, 3, exec, try_swap_workspace 3
bind = $mod, 4, exec, try_swap_workspace 4
bind = $mod, 5, exec, try_swap_workspace 5
bind = $mod, 6, exec, try_swap_workspace 6
bind = $mod, 7, exec, try_swap_workspace 7
bind = $mod, 8, exec, try_swap_workspace 8
bind = $mod, 9, exec, try_swap_workspace 9
bind = $mod, 0, exec, try_swap_workspace 10

# Move active window to a workspace with mod + SHIFT + [0-9]
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
bind = $mod, S, togglespecialworkspace, magic
bind = $mod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mod + scroll
bind = $mod, mouse_down, workspace, e-1
bind = $mod, mouse_up, workspace, e+1

# Move/resize windows with mod + LMB/RMB and dragging
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
