#$file = ~/Pictures/background/blueNebula.png
source = ~/.config/hypr/var-background.conf

splash = true

wallpaper {
  monitor = DP-2
  path = $file
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = $file
  fit_mode = cover
}

