splash = true

wallpaper {
  monitor = DP-2
  path = ~/Pictures/background/TheSeldowitchNebula.png
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = ~/Pictures/background/TheSeldowitchNebula.png
  fit_mode = cover
}

