splash = true

wallpaper {
  monitor = DP-3
  path = ~/Pictures/background/Hades_Launch.png 
  fit_mote = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = ~/Pictures/background/Hades_Launch.png 
  fit_mote = cover
}

