$black      = rgb(1d2021)
$black0     = rgb(141517)
$red        = rgb(ea6962)
$red0       = rgb(442e2d)
$green      = rgb(a9b665)
$green0     = rgb(333e34)
$yellow     = rgb(d8a657)
$yellow0    = rgb(473c29)
$blue       = rgb(7daea3)
$blue0      = rgb(e23b3b)
$purple     = rgb(d3869b)
$purple0    = rgb(3c333b)
$aqua       = rgb(89b482)
$white      = rgb(d4be98)
$white0     = rgb(ddc7a1)
